#!/bin/bash
# ------------------------------------------------------------
# script:  clean-puppet-reports
# Author:  Esteban M. Navas Martín
# Date:    12-01-2017
# Ver:     16-12-2022
#
# Purpose: This program cleans puppet reports
#
# Copyright (c) 2017-2022 Esteban M. Navas Martín <algodelinux@gmail.com>. All rights reserved.

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.

REPORTSDIR="/var/lib/puppet/reports/"

# Comprobamos si se han introducido la antigüedad como parámetro
if [ $# -lt 1 ]; then
   ANTIGUEDADMAX="180" # antigüedad máxima por defecto
else
   ANTIGUEDADMAX=$1
fi

echo "Eliminando puppet reports con más de $ANTIGUEDADMAX días de antiguedad..."
find $REPORTSDIR -not -type d -mtime +$ANTIGUEDADMAX
find $REPORTSDIR -not -type d -mtime +$ANTIGUEDADMAX -exec rm -rf {} +;
echo "Fin borrado puppet reports antiguos."
